[project]
name = "ai-agent-playground"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openmeteo-requests>=1.7.4",
    "pydantic-ai>=1.9.0",
    "python-dotenv>=1.2.1",
]
